# Generated by Django 5.1.6 on 2025-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='images',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hero',
            name='types',
            field=models.CharField(default='', max_length=100),
        ),
    ]
