# Generated by Django 5.1.6 on 2025-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoms', '0002_hero_images_hero_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='images',
            field=models.URLField(default=''),
        ),
    ]
